apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-db
  namespace: {{ .Values.namespace }}
  labels:
    id: {{ .Values.labels.id }}
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
data:
  MYSQL_DATABASE: {{ .Values.env.MYSQL_DATABASE }}
  MYSQL_USER: {{ .Values.env.MYSQL_USER }}
