apiVersion: v1
kind: Secret
metadata:
  name: db
  namespace: wordpress-db
  labels:
    id: c0908323
    app: mysql
    env: dev
type: Opaque
data:
#  MYSQL_USER: dXNlcg==              # Base64 encoded value for 'user'
  MYSQL_PASSWORD: cGFzc3dvcmQ=      # Base64 encoded value for 'password'
  MYSQL_ROOT_PASSWORD: bXlyb290cGFzcw==  # Base64 encoded value for 'myrootpass'
