apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-wp
  namespace: wordpress-app  # Set the namespace here
data:
  WORDPRESS_DB_HOST: "mysql.wordpress-db.svc.cluster.local"  # Adjust as needed
