apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress-app
  labels:
    id: c0908323
    app: wordpress
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: configmap-wp
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: app
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              value: db

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wordpress-app
  labels:
    id: c0908323
    app: wordpress
    env: dev
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#  type: LoadBalancer