apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: wordpress-app
type: Opaque
data:
  WORDPRESS_DB_USER: dXNlcg==         
  WORDPRESS_DB_PASSWORD: cGFzc3dvcmQ=  
  WORDPRESS_DB_NAME: ZGJfZ3JvdXA=      
