apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-wp
  namespace: {{ .Values.namespace }}
  labels:
    id: {{ .Values.labels.id }}
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
data:
  WORDPRESS_DB_HOST: "{{ .Values.wordpress.dbHost }}"
