apiVersion: v1
kind: Secret
metadata:
  name: app
  namespace: {{ .Values.namespace }}
  labels:
    id: {{ .Values.labels.id }}
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
type: Opaque
data:
  WORDPRESS_DB_USER: {{ .Values.secrets.WORDPRESS_DB_USER }}
  WORDPRESS_DB_PASSWORD: {{ .Values.secrets.WORDPRESS_DB_PASSWORD }}
  WORDPRESS_DB_NAME: {{ .Values.secrets.WORDPRESS_DB_NAME }}
